# Generated by Django 4.1.7 on 2023-03-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='approval',
            new_name='approved',
        ),
    ]
